name: Update README Activity

on:
  schedule:
    # Se ejecuta automáticamente cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: Actualizar README con actividad reciente
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Actualizar sección de actividad en README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Actualización automática de actividad en README"
          MAX_LINES: 5
